# Generated by Django 2.2.13 on 2020-08-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=200)),
                ('book_brief', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('book_name', models.CharField(max_length=200)),
                ('chapter_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('chapter_path', models.CharField(max_length=200)),
                ('chapter_id', models.IntegerField()),
            ],
        ),
    ]
