# Generated by Django 2.2.13 on 2020-08-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='series',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
