# Generated by Django 2.2.13 on 2020-08-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='book_id',
            field=models.IntegerField(null=True),
        ),
    ]
